<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    protected $fillable = [
        'report_type',
        'data',
        'generated_by',
    ];

    protected $casts = [
        'data' => 'array',  // Cast data as an array
    ];

    // Relationship with user (Generated by)
    public function generatedBy()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}
